-- 曲マスター（既存50曲 + 新規PD曲）
INSERT INTO songs (title, has_vocal, main_instrument, tempo, original_key, chords, lyrics, is_public_domain) VALUES
-- === トラディショナル / PD曲（歌詞あり） ===
('Man of Constant Sorrow', true, 'guitar', 'medium', 'D', 'Verse: Dm - Dm - C - Dm | Dm - Dm - C - Dm', E'I am a man of constant sorrow\nI''ve seen trouble all my days\nI bid farewell to old Kentucky\nThe place where I was born and raised', true),
('Will the Circle Be Unbroken', true, 'guitar', 'medium', 'A', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - G - C - G | G - G - D - G', E'Will the circle be unbroken\nBy and by Lord by and by\nThere''s a better home a-waiting\nIn the sky Lord in the sky', true),
('Roll in My Sweet Baby''s Arms', true, 'banjo', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - C - G - D - G', E'Roll in my sweet baby''s arms\nRoll in my sweet baby''s arms\nGonna lay around the shack\nTill the mail train comes back\nAnd roll in my sweet baby''s arms', true),
('Nine Pound Hammer', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'This nine pound hammer is a little too heavy\nFor my size honey for my size\nRoll on buddy don''t you roll so slow\nBaby how can I roll when the wheels won''t go', true),
('Old Joe Clark', true, 'fiddle', 'fast', 'A', 'Verse: A - G - A - G | A - G - A - A | Chorus: A - G - A - G | A - G - A - A', E'Old Joe Clark the preacher''s son\nPreached all over the plain\nThe only text he ever knew\nWas high low jack and the game\n\nChorus:\nFare thee well Old Joe Clark\nFare thee well I say\nFare thee well Old Joe Clark\nI ain''t got long to stay', true),
('I''ll Fly Away', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - G - C - G | G - G - D - G', E'Some glad morning when this life is o''er\nI''ll fly away\nTo a home on God''s celestial shore\nI''ll fly away\n\nChorus:\nI''ll fly away oh glory\nI''ll fly away in the morning\nWhen I die hallelujah by and by\nI''ll fly away', true),
('Amazing Grace', true, 'guitar', 'slow', 'G', 'Verse: G - G - C - G | G - G - D - G', E'Amazing grace how sweet the sound\nThat saved a wretch like me\nI once was lost but now am found\nWas blind but now I see', true),
('Angel Band', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'My latest sun is sinking fast\nMy race is nearly run\nMy strongest trials now are past\nMy triumph has begun\n\nChorus:\nOh come angel band come and around me stand\nOh bear me away on your snowy wings\nTo my immortal home', true),
('Wayfaring Stranger', true, 'guitar', 'slow', 'Am', 'Verse: Am - Am - F - Am | Am - Am - E - Am', E'I am a poor wayfaring stranger\nTraveling through this world of woe\nYet there''s no sickness toil nor danger\nIn that bright land to which I go\n\nChorus:\nI''m going there to see my father\nI''m going there no more to roam\nI''m only going over Jordan\nI''m only going over home', true),
('Down the Road', true, 'guitar', 'fast', 'G', 'Verse: G - C - G - D | G - C - D - G', E'Down the road about a mile or two\nLives a little girl named Pearly Blue\nAbout so high and her hair is brown\nThe prettiest thing boys in this town', true),
('Little Maggie', true, 'banjo', 'fast', 'G', 'Verse: G - G - F - G | G - G - F - G', E'Over yonder stands Little Maggie\nWith a dram glass in her hand\nShe''s drinking away her troubles\nShe''s courting another man', true),
('Shady Grove', true, 'mandolin', 'medium', 'Am', 'Verse: Am - Am - G - Am | Am - Am - G - Am', E'Shady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away\n\nCheeks as red as a blooming rose\nEyes are the prettiest brown\nShe''s the darling of my heart\nSweetest girl in town', true),
('John Henry', true, 'banjo', 'medium', 'E', 'Verse: G - G - C - G | G - G - D - G', E'John Henry was a little baby boy\nSitting on his daddy''s knee\nHe picked up a hammer and a little piece of steel\nSaid this hammer''s gonna be the death of me Lord Lord\nThis hammer''s gonna be the death of me', true),
('Bile Them Cabbage Down', true, 'banjo', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'Bile them cabbage down\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down', true),
('Long Journey Home', true, 'banjo', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'Black smoke a-rising and it surely is a train\nSurely is a train boys surely is a train\nBlack smoke a-rising and it surely is a train\nI''m on my long journey home', true),
('Wildwood Flower', true, 'guitar', 'medium', 'C', 'Verse: C - C - F - C | C - C - G - C', E'Oh I''ll twine with my mingles and waving black hair\nWith the roses so red and the lilies so fair\nAnd the myrtle so bright with the emerald dew\nThe pale and the leader and eyes look like blue', true),
('Keep on the Sunny Side', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | G - C - D - G', E'There''s a dark and a troubled side of life\nThere''s a bright and a sunny side too\nThough we meet with the darkness and strife\nThe sunny side we also may view\n\nChorus:\nKeep on the sunny side always on the sunny side\nKeep on the sunny side of life\nIt will help us every day it will brighten all the way\nIf we keep on the sunny side of life', true),
('Bury Me Beneath the Willow', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'Oh bury me beneath the willow\nUnder the weeping willow tree\nSo she may know where I am sleeping\nAnd perhaps she''ll weep for me', true),
('Hot Corn Cold Corn', true, 'banjo', 'fast', 'G', 'Verse: A - A - D - A | A - A - E - A', E'Hot corn cold corn bring along the demijohn\nHot corn cold corn bring along the demijohn\nHot corn cold corn bring along the demijohn\nFare you well Uncle Bill see you in the morning yes sir', true),
('Pretty Polly', true, 'banjo', 'slow', 'Dm', 'Verse: Dm - Dm - C - Dm | Dm - Dm - C - Dm', E'Oh Polly, Pretty Polly, come go along with me\nPolly, Pretty Polly, come go along with me\nBefore we get married\nSome pleasures to see', true),
('Banks of the Ohio', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - G - C - G | G - D - G - G', E'I asked my love to take a walk\nTo take a walk, just a little walk\nDown beside where the waters flow\nDown by the banks of the Ohio\n\nChorus:\nAnd only say that you''ll be mine\nIn no others arms entwine\nDown beside where the waters flow\nDown by the banks of the Ohio', true),
('East Virginia', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'I was born in East Virginia\nNorth Carolina I did go\nThere I met a fair young maiden\nAnd her name I did not know', true),
('Handsome Molly', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | G - C - D - G', E'I wish I was in London\nOr some other seaport town\nI''d set my foot on a steamboat\nAnd sail the ocean round', true),
('Little Birdie', true, 'banjo', 'medium', 'Am', 'Verse: Am - Am - G - Am | Am - Am - G - Am', E'Little birdie, little birdie\nCome and sing me your song\nI''ve a short while to be here\nAnd a long time to be gone', true),
('Darlin'' Corey', true, 'banjo', 'medium', 'Em', 'Verse: Em - Em - D - Em | Em - Em - D - Em', E'Wake up, wake up, darlin'' Corey\nWhat makes you sleep so sound\nThe revenue officers are coming\nGonna tear your still house down', true),
('Cindy', true, 'banjo', 'fast', 'G', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - G - C - G | G - G - D - G', E'I wish I was an apple\nA-hangin'' on a tree\nAnd every time my sweetheart passed\nShe''d take a bite of me\n\nChorus:\nGet along home, Cindy, Cindy\nGet along home, Cindy, Cindy\nGet along home, Cindy, Cindy\nI''ll marry you some day', true),
('Cumberland Gap', true, 'banjo', 'fast', 'A', 'Verse: A - A - G - A | A - A - G - A', E'Lay down boys and take a little nap\nLay down boys and take a little nap\nLay down boys and take a little nap\nForty-one miles to Cumberland Gap', true),
('Down in the Valley', true, 'guitar', 'slow', 'G', 'Verse: G - G - D - D | D - D - G - G', E'Down in the valley, the valley so low\nHang your head over, hear the wind blow\nHear the wind blow, dear, hear the wind blow\nHang your head over, hear the wind blow', true),
('Red River Valley', true, 'guitar', 'slow', 'G', 'Verse: G - G - C - G | G - C - D7 - G', E'From this valley they say you are going\nWe will miss your bright eyes and sweet smile\nFor they say you are taking the sunshine\nThat has brightened our path for a while', true),
('Little Sadie', true, 'guitar', 'fast', 'Am', 'Verse: Am - Am - G - Am | Am - Am - G - Am', E'Went out last night for to take a little round\nI met Little Sadie and I shot her down\nWent back home and I got in bed\nForty-four smokeless under my head', true),
('Rye Whiskey', true, 'guitar', 'medium', 'D', 'Verse: D - D - G - D | D - D - A - D', E'Rye whiskey, rye whiskey, rye whiskey I cry\nIf you don''t give me rye whiskey I surely will die\nIf the ocean was whiskey and I was a duck\nI''d dive to the bottom and never come up', true),
('Ground Hog', true, 'banjo', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'Shoulder up your gun and whistle up your dog\nShoulder up your gun and whistle up your dog\nWe''re off to the woods for to catch a ground hog\nGround hog!', true),
('Tom Dooley', true, 'guitar', 'medium', 'G', 'Verse: G - G - D - D | D - D - G - G', E'Hang down your head Tom Dooley\nHang down your head and cry\nHang down your head Tom Dooley\nPoor boy you''re bound to die', true),
('John Hardy', true, 'banjo', 'fast', 'Em', 'Verse: Em - Em - D - Em | Em - Em - D - Em', E'John Hardy was a desperate little man\nHe carried two guns every day\nHe shot a man on the West Virginia line\nAnd you ought to see John Hardy gettin'' away', true),
('Worried Man Blues', true, 'guitar', 'medium', 'G', 'Chorus: G - G - C - C | G - G - D7 - G', E'It takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long', true),
('Old Smoky', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'On top of Old Smoky, all covered with snow\nI lost my true lover, from courting too slow\nA-courting is pleasure, a-flirting is grief\nA false-hearted lover is worse than a thief', true),
('Swing Low Sweet Chariot', true, 'guitar', 'slow', 'D', 'Chorus: D - G - D - A | D - G - A - D', E'Swing low, sweet chariot\nComin'' for to carry me home\nSwing low, sweet chariot\nComin'' for to carry me home\n\nI looked over Jordan and what did I see\nComin'' for to carry me home\nA band of angels comin'' after me\nComin'' for to carry me home', true),
('Leaning on the Everlasting Arms', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | Chorus: G - C - G - D - G', E'What a fellowship, what a joy divine\nLeaning on the everlasting arms\nWhat a blessedness, what a peace is mine\nLeaning on the everlasting arms\n\nChorus:\nLeaning, leaning\nSafe and secure from all alarms\nLeaning, leaning\nLeaning on the everlasting arms', true),
('In the Sweet By and By', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | Chorus: G - C - G - D - G', E'There''s a land that is fairer than day\nAnd by faith we can see it afar\nFor the Father waits over the way\nTo prepare us a dwelling place there\n\nChorus:\nIn the sweet by and by\nWe shall meet on that beautiful shore\nIn the sweet by and by\nWe shall meet on that beautiful shore', true),
('Just a Closer Walk with Thee', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'I am weak but thou art strong\nJesus keep me from all wrong\nI''ll be satisfied as long\nAs I walk, let me walk close to thee\n\nChorus:\nJust a closer walk with thee\nGrant it Jesus is my plea\nDaily walking close to thee\nLet it be, dear Lord, let it be', true),
('Shall We Gather at the River', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'Shall we gather at the river\nWhere bright angel feet have trod\nWith its crystal tide forever\nFlowing by the throne of God\n\nChorus:\nYes we''ll gather at the river\nThe beautiful, the beautiful river\nGather with the saints at the river\nThat flows by the throne of God', true),
('What a Friend We Have in Jesus', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'What a friend we have in Jesus\nAll our sins and griefs to bear\nWhat a privilege to carry\nEverything to God in prayer', true),
('The Old Rugged Cross', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | Chorus: G - C - G - D - G', E'On a hill far away stood an old rugged cross\nThe emblem of suffering and shame\nAnd I love that old cross where the dearest and best\nFor a world of lost sinners was slain\n\nChorus:\nSo I''ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it some day for a crown', true),
('When the Saints Go Marching In', true, 'guitar', 'medium', 'G', 'Verse: G - G - G - G | C - C - G - G | G - E7 - Am - D7 | G - C - G - G', E'Oh when the saints go marching in\nOh when the saints go marching in\nLord how I want to be in that number\nWhen the saints go marching in', true),
('Precious Memories', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | Chorus: G - C - G - D - G', E'Precious memories unseen angels\nSent from somewhere to my soul\nHow they linger ever near me\nAnd the sacred past unfold\n\nChorus:\nPrecious memories how they linger\nHow they ever flood my soul\nIn the stillness of the midnight\nPrecious sacred scenes unfold', true),
('Lonesome Valley', true, 'guitar', 'slow', 'G', 'Verse: G - G - C - G | G - G - D - G', E'You gotta walk that lonesome valley\nYou gotta walk it by yourself\nAin''t nobody here can walk it for you\nYou gotta walk it by yourself', true),
('The Crawdad Song', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'You get a line and I''ll get a pole, honey\nYou get a line and I''ll get a pole, babe\nYou get a line and I''ll get a pole\nWe''ll go down to the crawdad hole\nHoney, sugar baby mine', true),
('Wabash Cannonball', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - C | G - G - D - G', E'From the great Atlantic ocean to the wide Pacific shore\nFrom the queen of flowing mountains to the south bells by the shore\nShe''s mighty tall and handsome and known quite well by all\nShe''s the combination on the Wabash Cannonball', true),
('This Train Is Bound for Glory', true, 'guitar', 'medium', 'G', 'Verse: G - G - C - G | G - G - D - G', E'This train is bound for glory this train\nThis train is bound for glory this train\nThis train is bound for glory\nDon''t carry nothing but the righteous and the holy\nThis train is bound for glory this train', true),
('Buffalo Gals', true, 'banjo', 'fast', 'G', 'Verse: G - G - D - D | D - D - G - G | Chorus: G - G - D - D | D - D - G - G', E'As I was walking down the street\nDown the street, down the street\nA pretty little gal I chanced to meet\nOh she was fair to view\n\nChorus:\nBuffalo gals won''t you come out tonight\nCome out tonight, come out tonight\nBuffalo gals won''t you come out tonight\nAnd dance by the light of the moon', true),
('The Cuckoo', true, 'banjo', 'medium', 'Am', 'Verse: Am - Am - G - Am | Am - Am - G - Am', E'Oh the cuckoo she''s a pretty bird\nShe warbles as she flies\nShe never says cuckoo\nTill the fourth day of July', true),
('Barbara Allen', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', E'In Scarlet Town where I was born\nThere was a fair maid dwelling\nMade every youth cry well-a-day\nHer name was Barbara Allen', true),
('Old Dan Tucker', true, 'banjo', 'fast', 'G', 'Verse: G - G - C - G | G - G - D - G | Chorus: G - G - C - G | G - G - D - G', E'Old Dan Tucker was a fine old man\nWashed his face in a frying pan\nCombed his hair with a wagon wheel\nDied with a toothache in his heel\n\nChorus:\nGet out the way Old Dan Tucker\nYou''re too late to get your supper\nSupper''s over and dinner''s cooking\nOld Dan Tucker just stand there looking', true),
('Jesse James', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | G - C - D - G | Chorus: G - C - G - D - G', E'Jesse James was a lad who killed many a man\nHe robbed the Glendale train\nHe stole from the rich and he gave to the poor\nHe''d a hand and a heart and a brain\n\nChorus:\nPoor Jesse had a wife to mourn for his life\nThree children they were brave\nBut that dirty little coward that shot Mister Howard\nHas laid poor Jesse in his grave', true),
('My Old Kentucky Home', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G | Chorus: G - C - G - D - G', E'The sun shines bright in the old Kentucky home\nTis summer the people are gay\nThe corn-top''s ripe and the meadow''s in the bloom\nWhile the birds make music all the day\n\nChorus:\nWeep no more my lady\nOh weep no more today\nWe will sing one song for the old Kentucky home\nFor the old Kentucky home far away', true),
('Camptown Races', true, 'banjo', 'fast', 'G', 'Verse: G - G - D - G | Chorus: G - C - G - D - G', E'The Camptown ladies sing this song\nDoo-dah doo-dah\nThe Camptown racetrack five miles long\nOh doo-dah day\n\nChorus:\nGoing to run all night\nGoing to run all day\nI''ll bet my money on a bobtail nag\nSomebody bet on the bay', true),
('Oh Susanna', true, 'banjo', 'fast', 'G', 'Verse: G - G - D - G | Chorus: C - C - G - D - G', E'I come from Alabama with a banjo on my knee\nI''m going to Louisiana my true love for to see\nIt rained all night the day I left the weather it was dry\nThe sun so hot I froze to death Susanna don''t you cry\n\nChorus:\nOh Susanna oh don''t you cry for me\nFor I come from Alabama\nWith a banjo on my knee', true),
('Omie Wise', true, 'guitar', 'slow', 'Em', 'Verse: Em - D - Em - Em | Em - D - Em - Em', E'Oh listen to my story I''ll tell you no lies\nHow John Lewis did murder poor little Omie Wise\nHe told her to meet him at Adams'' springs\nHe''d bring her some money and other fine things', true),
('Black Jack Davey', true, 'guitar', 'medium', 'Am', 'Verse: Am - G - Am - Am | Am - G - Am - Am', E'Black Jack Davey come a-ridin'' through the woods\nSinging so loud and merry\nHe charmed the heart of a lady fair\nThe wife of a wealthy squire', true),
-- === トラディショナル フィドルチューン（インスト） ===
('Cripple Creek', false, 'banjo', 'fast', 'A', 'A: A - D - A - E | A - D - E - A | B: A - D - A - E | A - D - E - A', NULL, true),
('Blackberry Blossom', false, 'fiddle', 'fast', 'G', 'A: Em - D - Em - D | Em - D - Em - Em | B: Em - D - Em - D | Em - D - Em - Em', NULL, true),
('Soldier''s Joy', false, 'fiddle', 'fast', 'D', 'A: D - D - A - D | D - D - A - D | B: D - G - D - A | D - G - A - D', NULL, true),
('Turkey in the Straw', false, 'fiddle', 'fast', 'G', 'Verse: G - G - C - G | G - G - D - G', E'As I was a-going on down the road\nWith a tired team and a heavy load\nI cracked my whip and the leader sprung\nI says day-day to the wagon tongue\n\nChorus:\nTurkey in the straw, turkey in the hay\nRoll ''em up and twist ''em up a high tuckahaw\nAnd twist ''em up a tune called Turkey in the Straw', true),
('Salt Creek', false, 'mandolin', 'fast', 'A', 'A: A - A - D - A | A - A - E - A | B: A - D - A - E | A - D - E - A', NULL, true),
('Red Haired Boy', false, 'fiddle', 'fast', 'A', 'A: A - G - A - G | A - G - A - E | B: A - G - A - G | A - G - E - A', NULL, true),
('Whiskey Before Breakfast', false, 'fiddle', 'fast', 'D', 'A: D - G - D - A | D - G - A - D | B: D - G - D - A | D - G - A - D', NULL, true),
('Fisher''s Hornpipe', false, 'fiddle', 'fast', 'D', 'A: D - G - D - A | D - G - A - D | B: D - G - D - A | D - G - A - D', NULL, true),
('Beaumont Rag', false, 'fiddle', 'fast', 'G', 'A: G - C - G - D | G - C - D - G | B: C - F - C - G | C - F - G - C', NULL, true),
('Sally Goodin', false, 'fiddle', 'fast', 'A', 'A - A - A - E | A - A - E - A', NULL, true),
('Arkansas Traveler', false, 'fiddle', 'medium', 'D', 'D - G - D - A7 | D - G - A7 - D', NULL, true),
('Devil''s Dream', false, 'fiddle', 'fast', 'A', 'A - D - A - E | A - D - E - A', NULL, true),
('Cotton-Eyed Joe', false, 'fiddle', 'fast', 'A', 'A - A - A - E | A - A - E - A', NULL, true),
('Ragtime Annie', false, 'fiddle', 'medium', 'D', 'D - G - D - A | D - G - A - D', NULL, true),
('Leather Britches', false, 'fiddle', 'fast', 'G', 'G - G - C - G | G - G - D - G', NULL, true),
('Cluck Old Hen', false, 'fiddle', 'medium', 'Am', 'Am - G - Am - Am | Am - G - Am - Am', NULL, true),
('Temperance Reel', false, 'fiddle', 'fast', 'G', 'G - C - G - D | G - C - D - G', NULL, true),
('Angeline the Baker', false, 'fiddle', 'medium', 'D', 'D - D - G - D | D - D - A - D', NULL, true),
('Sourwood Mountain', false, 'fiddle', 'medium', 'D', 'D - G - D - A | D - G - A - D', NULL, true),
('Liberty', false, 'fiddle', 'fast', 'D', 'D - G - D - A7 | D - G - A7 - D', NULL, true),
('Billy in the Lowground', false, 'fiddle', 'fast', 'C', 'C - Am - C - G | C - Am - G - C', NULL, true),
('June Apple', false, 'fiddle', 'medium', 'A', 'A - G - A - G | A - G - A - A', NULL, true),
('St. Anne''s Reel', false, 'fiddle', 'fast', 'D', 'D - G - D - A | D - G - A - D', NULL, true),
('Spotted Pony', false, 'fiddle', 'fast', 'Am', 'Am - G - Am - Em | Am - G - Em - Am', NULL, true),
('Fire on the Mountain', false, 'fiddle', 'fast', 'A', 'A - D - A - E | A - D - E - A', NULL, true),
('Cherokee Shuffle', false, 'fiddle', 'medium', 'A', 'A - D - A - E | A - D - E - A', NULL, true),
('Bonaparte''s Retreat', false, 'fiddle', 'medium', 'D', 'D - G - D - A | D - G - A - D', NULL, true),
('Dill Pickle Rag', false, 'guitar', 'fast', 'G', 'A: G - C - G - D7 | G - C - D7 - G | B: C - F - C - G7 | C - F - G7 - C', NULL, true),
-- === 著作権あり曲（コード進行のみ） ===
('Foggy Mountain Breakdown', false, 'banjo', 'fast', 'G', 'G - Em - G - D | G - Em - D - G', NULL, false),
('Blue Moon of Kentucky', true, 'mandolin', 'medium', 'B', 'Verse: B - E - B - F# | B - E - F# - B', NULL, false),
('Rocky Top', true, 'fiddle', 'fast', 'A', 'Verse: A - D - A - E | Chorus: A - D - A - E - A', NULL, false),
('Orange Blossom Special', false, 'fiddle', 'fast', 'E', 'E - A - E - B7 | E - A - B7 - E', NULL, false),
('Wagon Wheel', true, 'guitar', 'medium', 'G', 'Verse: G - D - Em - C | Chorus: G - D - C - C', NULL, false),
('I Am a Man of Constant Sorrow', true, 'guitar', 'medium', 'D', 'Verse: Dm - Dm - C - Dm | Dm - Dm - C - Dm', NULL, false),
('Big Mon', false, 'mandolin', 'fast', 'G', 'A: G - C - G - D | G - C - D - G', NULL, false),
('Gold Rush', false, 'banjo', 'fast', 'G', 'A: G - C - G - D | G - C - D - G | B: Em - C - Em - D', NULL, false),
('Sitting on Top of the World', true, 'guitar', 'medium', 'A', 'Verse: A - D - A - E | A - D - E - A', NULL, false),
('Dark Hollow', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | G - C - D - G', NULL, false),
('Footprints in the Snow', true, 'guitar', 'medium', 'G', 'Verse: G - C - G - D | Chorus: G - C - G - D - G', NULL, false),
('Blue Ridge Cabin Home', true, 'mandolin', 'medium', 'B', 'Verse: B - E - B - F# | B - E - F# - B', NULL, false),
('Molly and Tenbrooks', true, 'mandolin', 'fast', 'A', 'Verse: A - D - A - E | A - D - E - A', NULL, false),
('Uncle Pen', true, 'mandolin', 'fast', 'A', 'Verse: A - D - A - E | Chorus: A - D - A - E - A', NULL, false),
('Kentucky Waltz', true, 'fiddle', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', NULL, false),
('If I Needed You', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', NULL, false),
('High on a Mountain Top', true, 'guitar', 'medium', 'A', 'Verse: A - D - A - E | A - D - E - A', NULL, false),
('Ground Speed', false, 'mandolin', 'fast', 'A', 'A: A - D - A - E | A - D - E - A', NULL, false),
('Jerusalem Ridge', false, 'mandolin', 'fast', 'Am', 'A: Am - G - Am - E | Am - G - E - Am', NULL, false),
('Fireball Mail', false, 'guitar', 'fast', 'G', 'G - C - G - D | G - C - D - G', NULL, false),
('Rank Stranger', true, 'guitar', 'slow', 'G', 'Verse: G - C - G - D | G - C - D - G', NULL, false),
('How Mountain Girls Can Love', true, 'banjo', 'fast', 'A', 'Verse: A - D - A - E | Chorus: A - D - A - E - A', NULL, false)
ON CONFLICT (title) DO UPDATE SET
  chords = EXCLUDED.chords,
  lyrics = EXCLUDED.lyrics,
  is_public_domain = EXCLUDED.is_public_domain;

-- テストユーザー（auth.users + profiles を一括作成）
INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin,
  confirmation_token, recovery_token, email_change_token_new, email_change_token_current,
  email_change, phone_change, phone_change_token, reauthentication_token
) VALUES
  (
    'a1111111-1111-1111-1111-111111111111',
    '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated',
    'test.user@gmail.com',
    crypt('testpass', gen_salt('bf')),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"テストユーザー"}',
    false, '', '', '', '', '', '', '', ''
  ),
  (
    'a2222222-2222-2222-2222-222222222222',
    '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated',
    'tanaka@example.com',
    crypt('testpass', gen_salt('bf')),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"田中太郎"}',
    false, '', '', '', '', '', '', '', ''
  ),
  (
    'a3333333-3333-3333-3333-333333333333',
    '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated',
    'suzuki@example.com',
    crypt('testpass', gen_salt('bf')),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"鈴木花子"}',
    false, '', '', '', '', '', '', '', ''
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) VALUES
  ('a1111111-1111-1111-1111-111111111111', 'a1111111-1111-1111-1111-111111111111', 'test.user@gmail.com', 'email', '{"sub":"a1111111-1111-1111-1111-111111111111","email":"test.user@gmail.com"}', now(), now(), now()),
  ('a2222222-2222-2222-2222-222222222222', 'a2222222-2222-2222-2222-222222222222', 'tanaka@example.com', 'email', '{"sub":"a2222222-2222-2222-2222-222222222222","email":"tanaka@example.com"}', now(), now(), now()),
  ('a3333333-3333-3333-3333-333333333333', 'a3333333-3333-3333-3333-333333333333', 'suzuki@example.com', 'email', '{"sub":"a3333333-3333-3333-3333-333333333333","email":"suzuki@example.com"}', now(), now(), now())
;

INSERT INTO profiles (id, display_name, main_part, role) VALUES
  ('a1111111-1111-1111-1111-111111111111', 'テストユーザー', 'guitar', 'moderator'),
  ('a2222222-2222-2222-2222-222222222222', '田中太郎', 'banjo', 'user'),
  ('a3333333-3333-3333-3333-333333333333', '鈴木花子', 'fiddle', 'user')
ON CONFLICT (id) DO NOTHING;

-- テスト用レパートリー
INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a1111111-1111-1111-1111-111111111111', id, 'guitar', 'lead', 'ready', true
FROM songs WHERE title IN ('Foggy Mountain Breakdown', 'Rocky Top', 'Will the Circle Be Unbroken', 'Wagon Wheel', 'I''ll Fly Away')
ON CONFLICT (user_id, song_id) DO NOTHING;

INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a1111111-1111-1111-1111-111111111111', id, 'guitar', 'none', 'with_practice', false
FROM songs WHERE title IN ('Cripple Creek', 'Old Joe Clark', 'Amazing Grace')
ON CONFLICT (user_id, song_id) DO NOTHING;

INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a2222222-2222-2222-2222-222222222222', id, 'banjo', 'none', 'ready', true
FROM songs WHERE title IN ('Foggy Mountain Breakdown', 'Cripple Creek', 'Rocky Top', 'Gold Rush')
ON CONFLICT (user_id, song_id) DO NOTHING;

INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a2222222-2222-2222-2222-222222222222', id, 'banjo', 'harmony_high', 'with_practice', false
FROM songs WHERE title IN ('Will the Circle Be Unbroken', 'Wagon Wheel')
ON CONFLICT (user_id, song_id) DO NOTHING;

INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a3333333-3333-3333-3333-333333333333', id, 'fiddle', 'none', 'ready', false
FROM songs WHERE title IN ('Foggy Mountain Breakdown', 'Rocky Top', 'Orange Blossom Special', 'Old Joe Clark')
ON CONFLICT (user_id, song_id) DO NOTHING;

INSERT INTO user_repertoires (user_id, song_id, part, vocal, proficiency, is_favorite)
SELECT 'a3333333-3333-3333-3333-333333333333', id, 'fiddle', 'harmony_low', 'learning', false
FROM songs WHERE title IN ('Will the Circle Be Unbroken', 'Amazing Grace')
ON CONFLICT (user_id, song_id) DO NOTHING;


UPDATE songs SET lyrics = E'Old Joe Clark he had a house\nFifteen stories high\nAnd every story in that house\nWas filled with chicken pie\n\nFare thee well Old Joe Clark\nFare thee well I say\nFare thee well Old Joe Clark\nI ain''t got long to stay\n\nOld Joe Clark he had a dog\nAs blind as he could be\nRan a redbug round a stump\nAnd a coon up a hollow tree\n\nFare thee well Old Joe Clark\nFare thee well I say\nFare thee well Old Joe Clark\nI ain''t got long to stay\n\nOld Joe Clark he had a wife\nHer name was Betty Sue\nShe had two great big brown eyes\nThe other two were blue\n\nFare thee well Old Joe Clark\nFare thee well I say\nFare thee well Old Joe Clark\nI ain''t got long to stay\n\nI went down to Old Joe''s house\nHe invited me to supper\nI stumbled my toe on the table leg\nAnd stuck my nose in the butter\n\nFare thee well Old Joe Clark\nFare thee well I say\nFare thee well Old Joe Clark\nI ain''t got long to stay' WHERE title = 'Old Joe Clark';

UPDATE songs SET lyrics = E'I was standing by my window\nOn a cold and cloudy day\nWhen I saw the hearse come rolling\nFor to carry my mother away\n\nWill the circle be unbroken\nBy and by Lord by and by\nThere''s a better home a-waiting\nIn the sky Lord in the sky\n\nI told the undertaker\nUndertaker please drive slow\nFor this body you are hauling\nLord I hate to see her go\n\nWill the circle be unbroken\nBy and by Lord by and by\nThere''s a better home a-waiting\nIn the sky Lord in the sky\n\nI followed close behind her\nTried to hold up and be brave\nBut I could not hide my sorrow\nWhen they laid her in the grave\n\nWill the circle be unbroken\nBy and by Lord by and by\nThere''s a better home a-waiting\nIn the sky Lord in the sky' WHERE title = 'Will the Circle Be Unbroken';

UPDATE songs SET lyrics = E'I ain''t gonna work on the railroad\nI ain''t gonna work on the farm\nLay around the shack till the mail train comes back\nAnd roll in my sweet baby''s arms\n\nRoll in my sweet baby''s arms\nRoll in my sweet baby''s arms\nLay around the shack till the mail train comes back\nAnd roll in my sweet baby''s arms\n\nNow where were you last Friday night\nWhile I was lying in jail\nWalking the streets with another man\nWouldn''t even go my bail\n\nRoll in my sweet baby''s arms\nRoll in my sweet baby''s arms\nLay around the shack till the mail train comes back\nAnd roll in my sweet baby''s arms\n\nI know your parents don''t like me\nThey drove me away from your door\nIf I had my life to live over\nI''d never go there no more\n\nRoll in my sweet baby''s arms\nRoll in my sweet baby''s arms\nLay around the shack till the mail train comes back\nAnd roll in my sweet baby''s arms\n\nSometimes there''s a change in the ocean\nSometimes there''s a change in the sea\nSometimes there''s a change in my own true love\nBut there''s never a change in me\n\nRoll in my sweet baby''s arms\nRoll in my sweet baby''s arms\nLay around the shack till the mail train comes back\nAnd roll in my sweet baby''s arms' WHERE title = 'Roll in My Sweet Baby''s Arms';

UPDATE songs SET lyrics = E'This nine pound hammer is a little too heavy\nFor my size buddy for my size\nSo roll on buddy don''t you roll so slow\nHow can I roll when the wheels won''t go\n\nI''m going on the mountain just to see my baby\nAnd I ain''t coming back no I ain''t coming back\nSo roll on buddy don''t you roll so slow\nHow can I roll when the wheels won''t go\n\nIt''s a long way to Harlan it''s a long way to Hazard\nJust to get a little brew just to get a little brew\nSo roll on buddy don''t you roll so slow\nHow can I roll when the wheels won''t go\n\nThere ain''t one hammer in this tunnel\nThat rings like mine that rings like mine\nSo roll on buddy don''t you roll so slow\nHow can I roll when the wheels won''t go' WHERE title = 'Nine Pound Hammer';

UPDATE songs SET lyrics = E'Some glad morning when this life is o''er\nI''ll fly away\nTo a home on God''s celestial shore\nI''ll fly away\n\nI''ll fly away oh glory\nI''ll fly away in the morning\nWhen I die hallelujah by and by\nI''ll fly away\n\nWhen the shadows of this life have gone\nI''ll fly away\nLike a bird from prison bars has flown\nI''ll fly away\n\nI''ll fly away oh glory\nI''ll fly away in the morning\nWhen I die hallelujah by and by\nI''ll fly away\n\nJust a few more weary days and then\nI''ll fly away\nTo a land where joys shall never end\nI''ll fly away\n\nI''ll fly away oh glory\nI''ll fly away in the morning\nWhen I die hallelujah by and by\nI''ll fly away' WHERE title = 'I''ll Fly Away';

UPDATE songs SET lyrics = E'Amazing grace how sweet the sound\nThat saved a wretch like me\nI once was lost but now am found\nWas blind but now I see\n\n''Twas grace that taught my heart to fear\nAnd grace my fears relieved\nHow precious did that grace appear\nThe hour I first believed\n\nThrough many dangers toils and snares\nI have already come\n''Tis grace hath brought me safe thus far\nAnd grace will lead me home\n\nWhen we''ve been there ten thousand years\nBright shining as the sun\nWe''ve no less days to sing God''s praise\nThan when we first begun' WHERE title = 'Amazing Grace';

UPDATE songs SET lyrics = E'My latest sun is sinking fast\nMy race is nearly run\nMy strongest trials now are past\nMy triumph has begun\n\nOh come angel band\nCome and around me stand\nBear me away on your snow white wings\nTo my immortal home\nBear me away on your snow white wings\nTo my immortal home\n\nI know I''m near the holy ranks\nOf friends and kindred dear\nI''ve brushed the dew on Jordan''s banks\nThe crossing must be near\n\nOh come angel band\nCome and around me stand\nBear me away on your snow white wings\nTo my immortal home\nBear me away on your snow white wings\nTo my immortal home\n\nI''ve almost gained my heavenly home\nMy spirit loudly sings\nThe holy ones behold they come\nI hear the noise of wings\n\nOh come angel band\nCome and around me stand\nBear me away on your snow white wings\nTo my immortal home\nBear me away on your snow white wings\nTo my immortal home' WHERE title = 'Angel Band';

UPDATE songs SET lyrics = E'I am a poor wayfaring stranger\nTraveling through this world of woe\nYet there''s no sickness toil nor danger\nIn that bright land to which I go\nI''m going there to see my father\nI''m going there no more to roam\nI''m only going over Jordan\nI''m only going over home\n\nI know dark clouds will gather round me\nI know my way is rough and steep\nYet golden fields lie just before me\nWhere God''s redeemed shall ever sleep\nI''m going there to see my mother\nShe said she''d meet me when I come\nI''m only going over Jordan\nI''m only going over home\n\nI''ll soon be free from every trial\nMy body sleep in the old churchyard\nI''ll drop the cross of self-denial\nAnd enter on my great reward\nI''m going there to see my Savior\nTo sing His praise forevermore\nI''m only going over Jordan\nI''m only going over home' WHERE title = 'Wayfaring Stranger';

UPDATE songs SET lyrics = E'Down the road about a mile or two\nLives a little girl named Pearly Blue\nAbout so high and her hair is brown\nThe prettiest thing boys in this town\n\nNow every time I get the blues\nI walk the soles right off my shoes\nI don''t know why I love you so\nThat little girl lives down the road\n\nNow every time I go to town\nThe boys all kick my dog around\nMakes no difference what they say\nThat little dog is gonna pay\n\nDown the road down the road\nI''m gonna walk on down the road\nI don''t know why I love you so\nThat little girl lives down the road' WHERE title = 'Down the Road';

UPDATE songs SET lyrics = E'Over yonder stands Little Maggie\nWith a dram glass in her hand\nShe''s drinking away her troubles\nAnd courting some other man\n\nOh how can I ever stand it\nJust to see them two blue eyes\nA-shining in the moonlight\nLike two diamonds in the sky\n\nPretty flowers were made for blooming\nPretty stars were made to shine\nPretty women were made for loving\nLittle Maggie was made for mine\n\nLast time I saw Little Maggie\nShe was sitting on the banks of the sea\nWith a forty-four around her\nAnd a banjo on her knee' WHERE title = 'Little Maggie';

UPDATE songs SET lyrics = E'Shady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away\n\nCheeks as red as a blooming rose\nAnd eyes are the prettiest brown\nShe''s the darling of my heart\nSweetest little girl in town\n\nShady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away\n\nI wish I had a big fine horse\nAnd corn to feed him on\nAnd Shady Grove to stay at home\nAnd feed him while I''m gone\n\nShady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away\n\nWent to see my Shady Grove\nShe was standing in the door\nHer shoes and stockings in her hand\nAnd her little bare feet on the floor\n\nShady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away\n\nA kiss from pretty little Shady Grove\nIs sweet as brandy wine\nAnd there ain''t no girl in this whole world\nThat''s prettier than mine\n\nShady Grove my little love\nShady Grove I say\nShady Grove my little love\nI''m bound to go away' WHERE title = 'Shady Grove';

UPDATE songs SET lyrics = E'When John Henry was a little baby\nSitting on his papa''s knee\nHe picked up a hammer and a little piece of steel\nSaid this hammer''s gonna be the death of me Lord Lord\nThis hammer''s gonna be the death of me\n\nJohn Henry was a man just six feet high\nNearly two feet and a half across his breast\nHe''d hammer with a nine pound hammer all day\nAnd say give me a cool drink of water ''fore I rest Lord Lord\nGive me a cool drink of water ''fore I rest\n\nJohn Henry said to his captain\nA man ain''t nothing but a man\nBut before I let your steam drill beat me down\nI''ll die with a hammer in my hand Lord Lord\nI''ll die with a hammer in my hand\n\nJohn Henry hammering on the mountain\nHis hammer was striking fire\nHe drove so hard till he broke his poor heart\nAnd he laid down his hammer and he died Lord Lord\nHe laid down his hammer and he died\n\nThey took John Henry to the graveyard\nAnd they buried him in the sand\nAnd every locomotive come rolling by\nSays there lies a steel driving man Lord Lord\nThere lies a steel driving man' WHERE title = 'John Henry';

UPDATE songs SET lyrics = E'Bile them cabbage down boys\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down\n\nWent up on the mountain\nJust to give my horn a blow\nThought I heard my true love say\nYonder comes my beau\n\nBile them cabbage down boys\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down\n\nTook my gal to the blacksmith shop\nTo have her mouth made small\nShe turned around a time or two\nAnd swallowed shop and all\n\nBile them cabbage down boys\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down\n\nPossum in a simmon tree\nRaccoon on the ground\nRaccoon says you son of a gun\nShake some simmons down\n\nBile them cabbage down boys\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down\n\nSomeone stole my old coon dog\nWish they''d bring him back\nHe chased the big hogs through the fence\nAnd the little ones through the crack\n\nBile them cabbage down boys\nBake them hoecakes brown\nThe only song that I can sing\nIs bile them cabbage down' WHERE title = 'Bile Them Cabbage Down';

UPDATE songs SET lyrics = E'Black smoke a-rising and it surely is a train\nSurely is a train boys surely is a train\nBlack smoke a-rising and it surely is a train\nI''m on my long journey home\n\nLost all my money but a two dollar bill\nTwo dollar bill boys two dollar bill\nLost all my money but a two dollar bill\nI''m on my long journey home\n\nHomesick and lonesome and I''m feeling kind of blue\nFeeling kind of blue boys feeling kind of blue\nHomesick and lonesome and I''m feeling kind of blue\nI''m on my long journey home\n\nRaining and it''s storming and the moon gives no light\nMoon gives no light boys moon gives no light\nRaining and it''s storming and the moon gives no light\nI''m on my long journey home' WHERE title = 'Long Journey Home';

UPDATE songs SET lyrics = E'Oh I''ll twine with my mingles and waving black hair\nWith the roses so red and the lilies so fair\nAnd the myrtle so bright with the emerald dew\nThe pale and the leader and eyes look like blue\n\nOh I''ll dance I will sing and my laugh shall be gay\nI will charm every heart in his crown I will sway\nWhen I woke from my dreaming my idol was clay\nAll portions of loving had all flown away\n\nOh he taught me to love him and promised to love\nAnd to cherish me over all others above\nHow my heart is now wondering no misery can tell\nHe''s left me no warning no words of farewell' WHERE title = 'Wildwood Flower';

UPDATE songs SET lyrics = E'There''s a dark and a troubled side of life\nThere''s a bright and a sunny side too\nThough we meet with the darkness and strife\nThe sunny side we also may view\n\nKeep on the sunny side always on the sunny side\nKeep on the sunny side of life\nIt will help us every day it will brighten all the way\nIf we keep on the sunny side of life\n\nThe storm and its fury broke today\nCrushing hopes that we cherish so dear\nClouds and storms will in time pass away\nThe sun again will shine bright and clear\n\nKeep on the sunny side always on the sunny side\nKeep on the sunny side of life\nIt will help us every day it will brighten all the way\nIf we keep on the sunny side of life\n\nLet us greet with a song of hope each day\nThough the moment be cloudy or fair\nLet us trust in our Savior always\nWho keepeth everyone in His care\n\nKeep on the sunny side always on the sunny side\nKeep on the sunny side of life\nIt will help us every day it will brighten all the way\nIf we keep on the sunny side of life' WHERE title = 'Keep on the Sunny Side';

UPDATE songs SET lyrics = E'My heart is sad and I am lonely\nFor the only one I love\nWhen shall I see her oh no never\nTill we meet in heaven above\n\nOh bury me beneath the willow\nUnder the weeping willow tree\nSo she may know where I am sleeping\nAnd perhaps she''ll weep for me\n\nShe told me that she dearly loved me\nHow could it be untrue\nWhen she''s been gone and courting another\nOh I care not what I do\n\nOh bury me beneath the willow\nUnder the weeping willow tree\nSo she may know where I am sleeping\nAnd perhaps she''ll weep for me\n\nTomorrow was to be our wedding\nGod oh God where can she be\nShe''s out a-courting with another\nAnd no longer cares for me\n\nOh bury me beneath the willow\nUnder the weeping willow tree\nSo she may know where I am sleeping\nAnd perhaps she''ll weep for me' WHERE title = 'Bury Me Beneath the Willow';

UPDATE songs SET lyrics = E'I am a man of constant sorrow\nI''ve seen trouble all my days\nI bid farewell to old Kentucky\nThe place where I was born and raised\n\nFor six long years I''ve been in trouble\nNo pleasure here on earth I found\nFor in this world I''m bound to ramble\nI have no friends to help me now\n\nIt''s fare thee well my own true lover\nI never expect to see you again\nFor I''m bound to ride that northern railroad\nPerhaps I''ll die upon this train\n\nYou can bury me in some deep valley\nFor many years where I may lay\nThen you may learn to love another\nWhile I am sleeping in my grave\n\nMaybe your friends think I''m just a stranger\nMy face you never will see no more\nBut there is one promise that is given\nI''ll meet you on God''s golden shore' WHERE title = 'Man of Constant Sorrow';

UPDATE songs SET lyrics = E'Hot corn cold corn bring along the demijohn\nHot corn cold corn bring along the demijohn\nHot corn cold corn bring along the demijohn\nFare you well Uncle Bill see you in the morning\n\nUpstairs downstairs out in the kitchen\nUpstairs downstairs out in the kitchen\nUpstairs downstairs out in the kitchen\nSee Uncle Bill just a-raring and a-pitching\n\nOld Aunt Peggy won''t you fill ''em up again\nOld Aunt Peggy won''t you fill ''em up again\nOld Aunt Peggy won''t you fill ''em up again\nAin''t had a drink since I don''t know when' WHERE title = 'Hot Corn Cold Corn';

UPDATE songs SET lyrics = E'Oh Polly Pretty Polly come go along with me\nPolly Pretty Polly come go along with me\nBefore we get married some pleasures to see\n\nShe jumped up behind him and away they did go\nShe jumped up behind him and away they did go\nOver the hills and the valleys below\n\nHe led her over mountains and valleys so deep\nHe led her over mountains and valleys so deep\nAt last Pretty Polly she began for to weep\n\nOh Willie oh Willie I''m afraid of your ways\nOh Willie oh Willie I''m afraid of your ways\nThe way you''ve been rambling you''ll lead me astray\n\nHe stabbed her in the heart and the heart blood did flow\nHe stabbed her in the heart and the heart blood did flow\nAnd into the grave Pretty Polly did go' WHERE title = 'Pretty Polly';

UPDATE songs SET lyrics = E'I asked my love to take a walk\nTo take a walk just a little walk\nDown beside where the waters flow\nDown by the banks of the Ohio\n\nAnd only say that you''ll be mine\nIn no others arms entwine\nDown beside where the waters flow\nDown by the banks of the Ohio\n\nI held a knife against her breast\nAs into my arms she pressed\nShe cried oh Willie don''t murder me\nI''m not prepared for eternity\n\nAnd only say that you''ll be mine\nIn no others arms entwine\nDown beside where the waters flow\nDown by the banks of the Ohio\n\nI started home between twelve and one\nI cried my God what have I done\nKilled the only woman I loved\nBecause she would not be my bride\n\nAnd only say that you''ll be mine\nIn no others arms entwine\nDown beside where the waters flow\nDown by the banks of the Ohio\n\nI took her by her golden curls\nAnd drug her down to the riverside\nAnd there I threw her in to drown\nI watched her as she floated down\n\nAnd only say that you''ll be mine\nIn no others arms entwine\nDown beside where the waters flow\nDown by the banks of the Ohio' WHERE title = 'Banks of the Ohio';

UPDATE songs SET lyrics = E'I was born in East Virginia\nNorth Carolina I did go\nThere I met a fair young maiden\nAnd her name I did not know\n\nOh her hair was dark and curly\nAnd her cheeks were rosy red\nOn her breast she wore white lilies\nWhere I longed to lay my head\n\nI don''t want your greenback dollar\nI don''t want your watch and chain\nAll I want is your heart darling\nSay you''ll take me back again\n\nI''d rather be in some dark holler\nWhere the sun refuse to shine\nThan to see you be another man''s darling\nAnd to know you''ll never be mine' WHERE title = 'East Virginia';

UPDATE songs SET lyrics = E'I wish I was in London\nOr some other seaport town\nI''d set my foot in a steamboat\nI''d sail the ocean round\n\nWhile sailing round the ocean\nWhile sailing round the sea\nI''d think of Handsome Molly\nWherever she may be\n\nDon''t you remember Molly\nWhen you give me your right hand\nSaid if you ever marry\nThat I would be the man\n\nNow you''ve broke your promise\nGo home with who you please\nWhile my poor heart is aching\nYou''re lying at your ease' WHERE title = 'Handsome Molly';

UPDATE songs SET lyrics = E'Little birdie little birdie\nCome and sing to me your song\nI''ve a short while to be here\nAnd a long time to be gone\n\nLittle birdie little birdie\nWhat makes you fly so high\nIt''s because I am a true little bird\nAnd I do not fear to die\n\nLittle birdie little birdie\nWhat makes your head so red\nAfter all that I been through\nIt''s a wonder I ain''t dead\n\nI ain''t got no diamonds\nI ain''t got no rings\nBut I''ll bring you my heart darling\nI''ll give you anything' WHERE title = 'Little Birdie';

UPDATE songs SET lyrics = E'Wake up wake up darlin'' Corey\nWhat makes you sleep so sound\nThe revenue officers are coming\nGonna tear your still house down\n\nThe first time I seen darlin'' Corey\nShe was sitting by the sea\nWith a forty-four around her body\nAnd a banjo on her knee\n\nDig a hole dig a hole in the meadow\nDig a hole in the cold cold ground\nDig a hole dig a hole in the meadow\nGonna lay darlin'' Corey down\n\nGo away go away darlin'' Corey\nQuit hanging around my bed\nPretty women run me distracted\nCorn liquor has killed me dead' WHERE title = 'Darlin'' Corey';

UPDATE songs SET lyrics = E'You ought to see my Cindy\nShe lives way down south\nShe''s so sweet the honey bees\nSwarm around her mouth\n\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nI''ll marry you some day\n\nI wish I was an apple\nA-hanging in a tree\nAnd every time my sweetheart passed\nShe''d take a bite of me\n\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nI''ll marry you some day\n\nShe told me that she loved me\nShe called me sugar plum\nShe throwed her arms around me\nI thought my time had come\n\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nI''ll marry you some day\n\nCindy in the springtime\nCindy in the fall\nIf I can''t have my Cindy\nI''ll have no girl at all\n\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nGet along home Cindy Cindy\nI''ll marry you some day' WHERE title = 'Cindy';

UPDATE songs SET lyrics = E'Me and my wife and my wife''s pap\nWe all live down in Cumberland Gap\nCumberland Gap Cumberland Gap\nWay down yonder in Cumberland Gap\n\nCumberland Gap is a noted place\nThree kinds of water to wash your face\nCumberland Gap Cumberland Gap\nWay down yonder in Cumberland Gap\n\nCumberland Gap with its cliffs and rocks\nHome of the panther bear and fox\nCumberland Gap Cumberland Gap\nWay down yonder in Cumberland Gap\n\nLay down boys and take a little nap\nFourteen miles to Cumberland Gap\nCumberland Gap Cumberland Gap\nWay down yonder in Cumberland Gap' WHERE title = 'Cumberland Gap';

UPDATE songs SET lyrics = E'Down in the valley the valley so low\nHang your head over hear the wind blow\nHear the wind blow dear hear the wind blow\nHang your head over hear the wind blow\n\nRoses love sunshine violets love dew\nAngels in heaven know I love you\nKnow I love you dear know I love you\nAngels in heaven know I love you\n\nIf you don''t love me love whom you please\nThrow your arms round me give my heart ease\nGive my heart ease love give my heart ease\nThrow your arms round me give my heart ease\n\nWrite me a letter send it by mail\nSend it in care of Birmingham jail\nBirmingham jail love Birmingham jail\nSend it in care of Birmingham jail' WHERE title = 'Down in the Valley';

UPDATE songs SET lyrics = E'From this valley they say you are going\nWe will miss your bright eyes and sweet smile\nFor they say you are taking the sunshine\nThat has brightened our pathway awhile\n\nCome and sit by my side if you love me\nDo not hasten to bid me adieu\nBut remember the Red River Valley\nAnd the cowboy who loved you so true\n\nI''ve been thinking a long time my darling\nOf the sweet words you never would say\nNow alas must my fond hopes all vanish\nFor they say you are going away\n\nDo you think of the valley you''re leaving\nOh how lonely how sad it will be\nDo you think of the kind hearts you''re breaking\nAnd the pain you are causing to me' WHERE title = 'Red River Valley';

UPDATE songs SET lyrics = E'Went out last night to take a little round\nI met Little Sadie and I shot her down\nWent back home and I got in bed\nForty-four smokeless under my head\n\nI began to think about what I had done\nGrabbed my coat and away I run\nMade a good run but I ran too slow\nThey overtook me in Jericho\n\nStanding on the corner ringing my hands\nAlong come the sheriff and he took me in hand\nThrowed me in the jailhouse bound me down\nLocked me up in that old Jericho town\n\nThe judge and the jury they took their stand\nThe judge had the papers in his right hand\nForty-one days forty-one nights\nForty-one years to wear the ball and stripes' WHERE title = 'Little Sadie';

UPDATE songs SET lyrics = E'Rye whiskey rye whiskey rye whiskey I cry\nIf I don''t get rye whiskey I surely will die\nIf the ocean was whiskey and I was a duck\nI''d dive to the bottom and never come up\n\nI''ll eat when I''m hungry and drink when I''m dry\nIf the hard times don''t kill me I''ll live till I die\nRye whiskey rye whiskey rye whiskey I cry\nIf I don''t get rye whiskey I surely will die\n\nI''ll tune up my fiddle and I''ll rosin my bow\nI''ll make myself welcome wherever I go\nBeefsteak when I''m hungry red liquor when I''m dry\nGreenbacks when I''m hard up and heaven when I die\n\nJack of Diamonds Jack of Diamonds I know you of old\nYou''ve robbed my poor pockets of silver and gold\nRye whiskey rye whiskey rye whiskey I cry\nIf I don''t get rye whiskey I surely will die' WHERE title = 'Rye Whiskey';

UPDATE songs SET lyrics = E'Shoulder up your gun and whistle up your dog\nShoulder up your gun and whistle up your dog\nWe''re off to the woods for to catch a ground hog\nGround hog\n\nToo many rocks and too many logs\nToo many rocks to catch a ground hog\nGround hog\n\nHe''s in here boys the hole''s wore slick\nRun here Sam with your forked stick\nGround hog\n\nCome on Sam and let''s go to town\nI''ve got the ground hog sewed up sound\nGround hog' WHERE title = 'Ground Hog';

UPDATE songs SET lyrics = E'Hang down your head Tom Dooley\nHang down your head and cry\nHang down your head Tom Dooley\nPoor boy you''re bound to die\n\nI met her on the mountain\nThere I took her life\nMet her on the mountain\nStabbed her with my knife\n\nHang down your head Tom Dooley\nHang down your head and cry\nHang down your head Tom Dooley\nPoor boy you''re bound to die\n\nThis time tomorrow\nReckon where I''ll be\nHadn''t a been for Grayson\nI''d a been in Tennessee\n\nHang down your head Tom Dooley\nHang down your head and cry\nHang down your head Tom Dooley\nPoor boy you''re bound to die\n\nThis time tomorrow\nReckon where I''ll be\nDown in some lonesome valley\nHanging from a white oak tree\n\nHang down your head Tom Dooley\nHang down your head and cry\nHang down your head Tom Dooley\nPoor boy you''re bound to die' WHERE title = 'Tom Dooley';

UPDATE songs SET lyrics = E'John Hardy was a desperate little man\nHe carried two guns every day\nHe shot down a man on the West Virginia line\nYou ought to seen John Hardy getting away Lord Lord\nYou ought to seen John Hardy getting away\n\nJohn Hardy got to the East Stone bridge\nHe thought that he would be free\nAnd up stepped a man and took him by his arm\nSays Johnny come and go with me Lord Lord\nSays Johnny come and go with me\n\nHe sent for his papa and his mama too\nTo come and go his bail\nBut money won''t go a murderer''s bail\nAnd they locked John Hardy back in jail Lord Lord\nThey locked John Hardy back in jail\n\nJohn Hardy had a pretty little girl\nThe dress that she wore was blue\nAs she come skipping through the old jail hall\nSays Papa I''ve been true to you Lord Lord\nPapa I''ve been true to you' WHERE title = 'John Hardy';

UPDATE songs SET lyrics = E'It takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long\n\nI went across the river and I lay down to sleep\nI went across the river and I lay down to sleep\nI went across the river and I lay down to sleep\nWhen I woke up I had shackles on my feet\n\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long\n\nTwenty-nine links of chain around my leg\nTwenty-nine links of chain around my leg\nTwenty-nine links of chain around my leg\nAnd on each link an initial of my name\n\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long\n\nI asked the judge what might be my fine\nI asked the judge what might be my fine\nI asked the judge what might be my fine\nTwenty-one years on the Rocky Mountain Line\n\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long\n\nThe train arrived sixteen coaches long\nThe train arrived sixteen coaches long\nThe train arrived sixteen coaches long\nThe girl I love is on that train and gone\n\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nIt takes a worried man to sing a worried song\nI''m worried now but I won''t be worried long' WHERE title = 'Worried Man Blues';

UPDATE songs SET lyrics = E'On top of Old Smoky all covered with snow\nI lost my true lover come a-courting too slow\n\nA-courting is pleasure a-flirting is grief\nA false hearted lover is worse than a thief\n\nA thief will just rob you and take what you have\nBut a false hearted lover will lead you to the grave\n\nThe grave will decay you and turn you to dust\nNot one boy in a hundred a poor girl can trust' WHERE title = 'Old Smoky';

UPDATE songs SET lyrics = E'Swing low sweet chariot\nComing for to carry me home\nSwing low sweet chariot\nComing for to carry me home\n\nI looked over Jordan and what did I see\nComing for to carry me home\nA band of angels coming after me\nComing for to carry me home\n\nSwing low sweet chariot\nComing for to carry me home\nSwing low sweet chariot\nComing for to carry me home\n\nIf you get there before I do\nComing for to carry me home\nTell all my friends I''m coming too\nComing for to carry me home\n\nSwing low sweet chariot\nComing for to carry me home\nSwing low sweet chariot\nComing for to carry me home\n\nI''m sometimes up and sometimes down\nComing for to carry me home\nBut still my soul feels heavenly bound\nComing for to carry me home\n\nSwing low sweet chariot\nComing for to carry me home\nSwing low sweet chariot\nComing for to carry me home' WHERE title = 'Swing Low Sweet Chariot';

UPDATE songs SET lyrics = E'What a fellowship what a joy divine\nLeaning on the everlasting arms\nWhat a blessedness what a peace is mine\nLeaning on the everlasting arms\n\nLeaning leaning\nSafe and secure from all alarms\nLeaning leaning\nLeaning on the everlasting arms\n\nOh how sweet to walk in this pilgrim way\nLeaning on the everlasting arms\nOh how bright the path grows from day to day\nLeaning on the everlasting arms\n\nLeaning leaning\nSafe and secure from all alarms\nLeaning leaning\nLeaning on the everlasting arms\n\nWhat have I to dread what have I to fear\nLeaning on the everlasting arms\nI have blessed peace with my Lord so near\nLeaning on the everlasting arms\n\nLeaning leaning\nSafe and secure from all alarms\nLeaning leaning\nLeaning on the everlasting arms' WHERE title = 'Leaning on the Everlasting Arms';

UPDATE songs SET lyrics = E'There''s a land that is fairer than day\nAnd by faith we can see it afar\nFor the Father waits over the way\nTo prepare us a dwelling place there\n\nIn the sweet by and by\nWe shall meet on that beautiful shore\nIn the sweet by and by\nWe shall meet on that beautiful shore\n\nWe shall sing on that beautiful shore\nThe melodious songs of the blessed\nAnd our spirits shall sorrow no more\nNot a sigh for the blessing of rest\n\nIn the sweet by and by\nWe shall meet on that beautiful shore\nIn the sweet by and by\nWe shall meet on that beautiful shore\n\nTo our bountiful Father above\nWe will offer our tribute of praise\nFor the glorious gift of His love\nAnd the blessings that hallow our days\n\nIn the sweet by and by\nWe shall meet on that beautiful shore\nIn the sweet by and by\nWe shall meet on that beautiful shore' WHERE title = 'In the Sweet By and By';

UPDATE songs SET lyrics = E'I am weak but Thou art strong\nJesus keep me from all wrong\nI''ll be satisfied as long\nAs I walk let me walk close to Thee\n\nJust a closer walk with Thee\nGrant it Jesus is my plea\nDaily walking close to Thee\nLet it be dear Lord let it be\n\nThrough this world of toil and snares\nIf I falter Lord who cares\nWho with me my burden shares\nNone but Thee dear Lord none but Thee\n\nJust a closer walk with Thee\nGrant it Jesus is my plea\nDaily walking close to Thee\nLet it be dear Lord let it be\n\nWhen my feeble life is o''er\nTime for me will be no more\nGuide me gently safely o''er\nTo Thy kingdom shore to Thy shore\n\nJust a closer walk with Thee\nGrant it Jesus is my plea\nDaily walking close to Thee\nLet it be dear Lord let it be' WHERE title = 'Just a Closer Walk with Thee';

UPDATE songs SET lyrics = E'Shall we gather at the river\nWhere bright angel feet have trod\nWith its crystal tide forever\nFlowing by the throne of God\n\nYes we''ll gather at the river\nThe beautiful the beautiful river\nGather with the saints at the river\nThat flows by the throne of God\n\nOn the margin of the river\nWashing up its silver spray\nWe will walk and worship ever\nAll the happy golden day\n\nYes we''ll gather at the river\nThe beautiful the beautiful river\nGather with the saints at the river\nThat flows by the throne of God\n\nSoon we''ll reach the shining river\nSoon our pilgrimage will cease\nSoon our happy hearts will quiver\nWith the melody of peace\n\nYes we''ll gather at the river\nThe beautiful the beautiful river\nGather with the saints at the river\nThat flows by the throne of God' WHERE title = 'Shall We Gather at the River';

UPDATE songs SET lyrics = E'What a friend we have in Jesus\nAll our sins and griefs to bear\nWhat a privilege to carry\nEverything to God in prayer\nOh what peace we often forfeit\nOh what needless pain we bear\nAll because we do not carry\nEverything to God in prayer\n\nHave we trials and temptations\nIs there trouble anywhere\nWe should never be discouraged\nTake it to the Lord in prayer\nCan we find a friend so faithful\nWho will all our sorrows share\nJesus knows our every weakness\nTake it to the Lord in prayer\n\nAre we weak and heavy laden\nCumbered with a load of care\nPrecious Savior still our refuge\nTake it to the Lord in prayer\nDo thy friends despise forsake thee\nTake it to the Lord in prayer\nIn His arms He''ll take and shield thee\nThou wilt find a solace there' WHERE title = 'What a Friend We Have in Jesus';

UPDATE songs SET lyrics = E'On a hill far away stood an old rugged cross\nThe emblem of suffering and shame\nAnd I love that old cross where the dearest and best\nFor a world of lost sinners was slain\n\nSo I''ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it some day for a crown\n\nOh that old rugged cross so despised by the world\nHas a wondrous attraction for me\nFor the dear Lamb of God left His glory above\nTo bear it to dark Calvary\n\nSo I''ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it some day for a crown\n\nTo that old rugged cross I will ever be true\nIts shame and reproach gladly bear\nThen He''ll call me some day to my home far away\nWhere His glory forever I''ll share\n\nSo I''ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it some day for a crown' WHERE title = 'The Old Rugged Cross';

UPDATE songs SET lyrics = E'Oh when the saints go marching in\nOh when the saints go marching in\nLord how I want to be in that number\nWhen the saints go marching in\n\nOh when the sun refuse to shine\nOh when the sun refuse to shine\nLord how I want to be in that number\nWhen the sun refuse to shine\n\nOh when the stars have disappeared\nOh when the stars have disappeared\nLord how I want to be in that number\nWhen the stars have disappeared\n\nOh when the day of judgment comes\nOh when the day of judgment comes\nLord how I want to be in that number\nWhen the day of judgment comes' WHERE title = 'When the Saints Go Marching In';

UPDATE songs SET lyrics = E'Precious memories unseen angels\nSent from somewhere to my soul\nHow they linger ever near me\nAnd the sacred past unfold\n\nPrecious memories how they linger\nHow they ever flood my soul\nIn the stillness of the midnight\nPrecious sacred scenes unfold\n\nPrecious father loving mother\nFly across the lonely years\nAnd old home scenes of my childhood\nIn fond memory appears\n\nPrecious memories how they linger\nHow they ever flood my soul\nIn the stillness of the midnight\nPrecious sacred scenes unfold\n\nAs I travel on life''s pathway\nKnow not what the years may hold\nAs I ponder hope grows fonder\nPrecious memories flood my soul\n\nPrecious memories how they linger\nHow they ever flood my soul\nIn the stillness of the midnight\nPrecious sacred scenes unfold' WHERE title = 'Precious Memories';

UPDATE songs SET lyrics = E'Jesus walked this lonesome valley\nHe had to walk it by Himself\nOh nobody else could walk it for Him\nHe had to walk it by Himself\n\nWe must walk this lonesome valley\nWe have to walk it by ourselves\nOh nobody else can walk it for us\nWe have to walk it by ourselves\n\nYou must go and stand your trial\nYou have to stand it by yourself\nOh nobody else can stand it for you\nYou have to stand it by yourself' WHERE title = 'Lonesome Valley';

UPDATE songs SET lyrics = E'You get a line and I''ll get a pole honey\nYou get a line and I''ll get a pole babe\nYou get a line and I''ll get a pole\nWe''ll go fishing in the crawdad hole\nHoney sugar baby mine\n\nGet up old man you slept too late honey\nGet up old man you slept too late babe\nGet up old man you slept too late\nLast piece of crawdad''s on your plate\nHoney sugar baby mine\n\nAlong come a man with a sack on his back honey\nAlong come a man with a sack on his back babe\nAlong come a man with a sack on his back\nPacking all the crawdads he can pack\nHoney sugar baby mine\n\nThe old duck said to the drake honey\nThe old duck said to the drake babe\nThe old duck said to the drake\nThere ain''t no crawdads in this lake\nHoney sugar baby mine' WHERE title = 'The Crawdad Song';

UPDATE songs SET lyrics = E'From the great Atlantic Ocean to the wide Pacific shore\nFrom the queen of flowing mountains to the south bells by the shore\nShe''s mighty tall and handsome and known quite well by all\nShe''s the combination on the Wabash Cannonball\n\nShe came down from Birmingham one cold December day\nAs she rolled into the station you could hear all the people say\nThere''s a gal from Tennessee she''s long and she''s tall\nShe came down from Birmingham on the Wabash Cannonball\n\nOur eastern states are dandy so the people always say\nFrom New York to St Louis and Chicago by the way\nFrom the hills of Minnesota where the rippling waters fall\nNo changes can be taken on the Wabash Cannonball\n\nListen to the jingle the rumble and the roar\nAs she glides along the woodlands through the hills and by the shore\nHear the mighty rush of the engine hear the lonesome hobo''s call\nYou''re traveling through the jungle on the Wabash Cannonball' WHERE title = 'Wabash Cannonball';

UPDATE songs SET lyrics = E'This train is bound for glory this train\nThis train is bound for glory this train\nThis train is bound for glory\nDon''t carry nothing but the righteous and the holy\nThis train is bound for glory this train\n\nThis train don''t carry no gamblers this train\nThis train don''t carry no gamblers this train\nThis train don''t carry no gamblers\nNo hypocrites no midnight ramblers\nThis train don''t carry no gamblers this train\n\nThis train don''t carry no liars this train\nThis train don''t carry no liars this train\nThis train don''t carry no liars\nShe''s streamlined and a midnight flyer\nThis train don''t carry no liars this train\n\nThis train don''t carry no rustlers this train\nThis train don''t carry no rustlers this train\nThis train don''t carry no rustlers\nSidestreet walkers two-bit hustlers\nThis train don''t carry no rustlers this train' WHERE title = 'This Train Is Bound for Glory';

UPDATE songs SET lyrics = E'As I was walking down the street\nDown the street down the street\nA pretty little gal I chanced to meet\nOh she was fair to view\n\nBuffalo gals won''t you come out tonight\nCome out tonight come out tonight\nBuffalo gals won''t you come out tonight\nAnd dance by the light of the moon\n\nI asked her would she have some talk\nHave some talk have some talk\nHer feet covered up the whole sidewalk\nAs she stood close to me\n\nBuffalo gals won''t you come out tonight\nCome out tonight come out tonight\nBuffalo gals won''t you come out tonight\nAnd dance by the light of the moon\n\nI asked her would she have a dance\nHave a dance have a dance\nI thought that I might get a chance\nTo shake a foot with her\n\nBuffalo gals won''t you come out tonight\nCome out tonight come out tonight\nBuffalo gals won''t you come out tonight\nAnd dance by the light of the moon' WHERE title = 'Buffalo Gals';

UPDATE songs SET lyrics = E'Oh the cuckoo she''s a pretty bird\nShe warbles as she flies\nShe never says cuckoo\nTill the fourth day of July\n\nI''ve played cards in England\nI''ve played cards in Spain\nI''ll bet you ten dollars\nI''ll beat you next game\n\nJack of Diamonds Jack of Diamonds\nI know you of old\nYou''ve robbed my poor pockets\nOf silver and gold\n\nI wish I was a-sitting\nOn a mountain so high\nI''d look down on my true love\nWho told me goodbye' WHERE title = 'The Cuckoo';

UPDATE songs SET lyrics = E'In Scarlet town where I was born\nThere was a fair maid dwellin''\nMade every youth cry well-a-day\nHer name was Barbara Allen\n\n''Twas in the merry month of May\nWhen green buds they were swellin''\nYoung William Green on his death bed lay\nFor love of Barbara Allen\n\nHe sent his servant to the town\nTo the place where she was dwellin''\nSays my master''s sick bids me call for you\nIf your name be Barbara Allen\n\nSo slowly slowly she got up\nAnd slowly she came nigh him\nAnd all she said when she got there\nYoung man I think you''re dying\n\nHe turned his face unto the wall\nAnd death was drawing nigh him\nFarewell farewell to all my friends\nBe kind to Barbara Allen' WHERE title = 'Barbara Allen';

UPDATE songs SET lyrics = E'I came to town the other night\nI heard the noise and saw the fight\nI pulled old Dan Tucker out of the briar\nAnd kicked him in the head with my left hind tire\n\nGet out the way Old Dan Tucker\nYou''re too late to get your supper\nSupper''s over and dinner''s cooking\nOld Dan Tucker just stand there looking\n\nOld Dan Tucker was a fine old man\nWashed his face in a frying pan\nCombed his hair with a wagon wheel\nDied with a toothache in his heel\n\nGet out the way Old Dan Tucker\nYou''re too late to get your supper\nSupper''s over and dinner''s cooking\nOld Dan Tucker just stand there looking\n\nOld Dan Tucker climbed a tree\nHis Lord and Master for to see\nThe limb it broke and Dan got a fall\nNever got to see his Lord at all\n\nGet out the way Old Dan Tucker\nYou''re too late to get your supper\nSupper''s over and dinner''s cooking\nOld Dan Tucker just stand there looking\n\nOld Dan Tucker he got drunk\nHe fell in the fire and kicked up a chunk\nA red hot coal rolled in his shoe\nAnd oh my lordy how the ashes flew\n\nGet out the way Old Dan Tucker\nYou''re too late to get your supper\nSupper''s over and dinner''s cooking\nOld Dan Tucker just stand there looking' WHERE title = 'Old Dan Tucker';

UPDATE songs SET lyrics = E'Jesse James was a lad who killed many a man\nHe robbed the Glendale train\nHe stole from the rich and he gave to the poor\nHe''d a hand and a heart and a brain\n\nPoor Jesse had a wife to mourn for his life\nThree children they were brave\nBut that dirty little coward that shot Mister Howard\nHas laid poor Jesse in his grave\n\nIt was Robert Ford that dirty little coward\nI wonder how he does feel\nFor he ate of Jesse''s bread and he slept in Jesse''s bed\nThen he laid poor Jesse in his grave\n\nPoor Jesse had a wife to mourn for his life\nThree children they were brave\nBut that dirty little coward that shot Mister Howard\nHas laid poor Jesse in his grave\n\nIt was on a Saturday night the moon was shining bright\nThey robbed the Glendale train\nWith the agent on his knees he delivered up the keys\nTo the outlaws Frank and Jesse James\n\nPoor Jesse had a wife to mourn for his life\nThree children they were brave\nBut that dirty little coward that shot Mister Howard\nHas laid poor Jesse in his grave\n\nIt was on a Wednesday night the moon was shining bright\nThey robbed the Union train\nAnd the people they did say for many miles away\nIt was robbed by Frank and Jesse James\n\nPoor Jesse had a wife to mourn for his life\nThree children they were brave\nBut that dirty little coward that shot Mister Howard\nHas laid poor Jesse in his grave' WHERE title = 'Jesse James';

UPDATE songs SET lyrics = E'The sun shines bright in the old Kentucky home\n''Tis summer the people are gay\nThe corn top''s ripe and the meadow''s in the bloom\nWhile the birds make music all the day\n\nWeep no more my lady\nOh weep no more today\nWe will sing one song for the old Kentucky home\nFor the old Kentucky home far away\n\nThey hunt no more for the possum and the coon\nOn the meadow the hill and the shore\nThey sing no more by the glimmer of the moon\nOn the bench by the old cabin door\n\nWeep no more my lady\nOh weep no more today\nWe will sing one song for the old Kentucky home\nFor the old Kentucky home far away\n\nThe head must bow and the back will have to bend\nWherever the people may go\nA few more days and the trouble all will end\nIn the field where the sugar canes grow\n\nWeep no more my lady\nOh weep no more today\nWe will sing one song for the old Kentucky home\nFor the old Kentucky home far away' WHERE title = 'My Old Kentucky Home';

UPDATE songs SET lyrics = E'The Camptown ladies sing this song\nDoo dah doo dah\nThe Camptown racetrack five miles long\nOh the doo dah day\n\nGoing to run all night\nGoing to run all day\nI''ll bet my money on a bob-tailed nag\nSomebody bet on the bay\n\nThe long-tailed filly and the big black horse\nDoo dah doo dah\nThey fly the track and they both cut across\nOh the doo dah day\n\nGoing to run all night\nGoing to run all day\nI''ll bet my money on a bob-tailed nag\nSomebody bet on the bay\n\nOld muley cow come on to the track\nDoo dah doo dah\nThe bob-tailed filly threw her over his back\nOh the doo dah day\n\nGoing to run all night\nGoing to run all day\nI''ll bet my money on a bob-tailed nag\nSomebody bet on the bay' WHERE title = 'Camptown Races';

UPDATE songs SET lyrics = E'I come from Alabama with my banjo on my knee\nI''m going to Louisiana my true love for to see\nIt rained all night the day I left the weather it was dry\nThe sun so hot I froze to death Susanna don''t you cry\n\nOh Susanna oh don''t you cry for me\nFor I come from Alabama with my banjo on my knee\n\nI had a dream the other night when everything was still\nI thought I saw Susanna a-coming down the hill\nThe buckwheat cake was in her mouth the tear was in her eye\nSays I I''m coming from the south Susanna don''t you cry\n\nOh Susanna oh don''t you cry for me\nFor I come from Alabama with my banjo on my knee\n\nI soon will be in New Orleans and then I''ll look around\nAnd when I find Susanna I''ll fall upon the ground\nBut if I do not find her then I will surely die\nAnd when I''m dead and buried Susanna don''t you cry\n\nOh Susanna oh don''t you cry for me\nFor I come from Alabama with my banjo on my knee' WHERE title = 'Oh Susanna';

UPDATE songs SET lyrics = E'I''ll tell you all a story about Omie Wise\nHow she was deluded by John Lewis''s lies\nHe told her to meet him at Adams''s spring\nHe''d bring her some money and other fine things\n\nShe met him at the spring where she did not fear\nSays now John Lewis let us go from here\nShe got up behind him and away they did go\nThey rode till they came where the deep river flowed\n\nNow Omie oh Omie I''ll tell you my mind\nMy mind is to drown you and leave you behind\nOh pity your infant and spare me my life\nLet me go rejected and not be your wife\n\nHe kissed her and hugged her and turned her around\nThen pushed her in deep water where he knew that she''d drown\nHe jumped on his pony and away he did ride\nAs the screams of poor Omie came down from the tide\n\nThe wretch was not punished until one day\nThey found Omie''s body and it floated away\nThey sent after John Lewis who tried for to flee\nThey caught him at old Hillsville in Adams County' WHERE title = 'Omie Wise';

UPDATE songs SET lyrics = E'Late last night when the boss man come home\nHe asked about his lady\nThe only answer he received\nShe''s gone with the Black Jack Davey\nShe''s gone with the Black Jack Davey\n\nGo saddle me up my milk white steed\nThe grey is not so speedy\nI''ll ride all night till the broad daylight\nTill I overtake my lady\nTill I overtake my lady\n\nHe rode and he rode till he came to the town\nAnd he searched till he found her\nShe was lying on a big four-poster bed\nIn the arms of the Black Jack Davey\nIn the arms of the Black Jack Davey\n\nWon''t you pull off them high heeled shoes\nAll made of Spanish leather\nWon''t you put on them low heeled shoes\nAnd we''ll ride home together\nAnd we''ll ride home together' WHERE title = 'Black Jack Davey';

UPDATE songs SET lyrics = E'As I was a-going on down the road\nWith a tired team and a heavy load\nI cracked my whip and the leader sprung\nI says day-day to the wagon tongue\n\nTurkey in the straw turkey in the hay\nRoll ''em up and twist ''em up a high tuckahaw\nAnd twist ''em up a tune called Turkey in the Straw\n\nWent out to milk and I didn''t know how\nI milked the goat instead of the cow\nA monkey sitting on a pile of straw\nA-winking at his mother-in-law\n\nTurkey in the straw turkey in the hay\nRoll ''em up and twist ''em up a high tuckahaw\nAnd twist ''em up a tune called Turkey in the Straw\n\nMet Mister Catfish coming down stream\nSays Mister Catfish what does you mean\nCaught Mister Catfish by the snout\nAnd turned Mister Catfish wrong side out\n\nTurkey in the straw turkey in the hay\nRoll ''em up and twist ''em up a high tuckahaw\nAnd twist ''em up a tune called Turkey in the Straw' WHERE title = 'Turkey in the Straw';
